server:
   port: 8001
   
# 定义当前服务名
spring:
   application:
      name: user
#   redis:
#      database: 0
#      host: 127.0.0.1
#      port: 6379
#      password: 
# 配置Eureka 服务器的地址
eureka:
   client:
      serviceUrl:
         defaultZone: http://es1:8000/eureka,http://es2:7999/eureka
         
# yml支持同一个文件内部的配置块, 使用 --- 分隔每一个配置块, 每个配置块都必须有个名字, 没有名字作为默认配置块
---
server:
   port: 8005
# 配置块名
spring:
   profiles: user8005
   
---
server:
   port: 8006
# 配置块名
spring:
   profiles: user8006
