server:
   port: 8001
   
# 定义当前服务名
spring:
   application:
      name: crbook
   datasource:
      url: jdbc:mysql://127.0.0.1/C85-S3-Ply-crbook?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver