server:
   port: 80

spring:
  application:
     name: crzuul
     
zuul:
   # 敏感头设置: 1. zuul 默认情况下回屏蔽某些http请求头域值, 2.要通过设置开启敏感头不过滤
   # sensitiveHeaders: Cookie,Set-Cookie,Authorization 默认过滤头
   sensitiveHeaders: 
   routes:
      # 路由名 == 服务名
      test: 
         path: /simple/163
         url: http://www.163.com
      # crbook 服务名映射 到 book
      crbook: /book/**
      # cruser 服务名映射 到 user
      cruser: /user/**
      # 默认路由
      base:
         path: /**
         serviceId: crindex

# 解决 zuul 网关报错的问题
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
